; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define Registered
#define SetupName "LiveMirrorSetup"
;#define README_FILE "..\License\Readme.txt"
;#define LICENSE_FILE "..\License\License.txt"
#include "install.iss"
